#!/bin/sh

if [ "${1}" = '' ]; then
	echo 'Kernel installer for Lenny'
	echo "Usage: ${0##*/} /path/to/newrootfs [--no-resolvconf]"
	echo ''
	echo 'During installation, apt will ask for something related'
	echo 'to initrd and you will be given the option to abort'
	echo 'the installation or not.'
	echo 'Initrd will be generated by initramfs-tools'
	echo 'and detected by update-grub.'
	echo 'After the installation is completed,'
	echo 'the system is ready for the first boot.'
	exit 1
fi
[ ! "${2}" = '--no-resolvconf' ] && if [ ! -e '/etc/resolv.conf' ]; then
	echo '/etc/resolv.conf not found'
	exit 1
fi
if [ ! -d "${1}" ]; then
	echo "${1} is not a directory"
	exit 1
fi
if [ ! -e "${1}/etc/debian_version" ]; then
	echo 'This is not a debian'
	exit 1
fi
if [ "$(sed 's/\..*//' ${1}/etc/debian_version)" -ge '6' ]; then
	echo 'This debian is newer than lenny'
	echo 'You do not have to use this script'
	exit 1
fi

arch=$(chroot "${1}" dpkg --print-architecture)
update_grub='true'

if [ "${arch}" = '' ]; then
	echo 'Architecture detection failed'
	exit 1
fi

remove_resolvconf='true'
[ -e "${1}/etc/resolv.conf" ] && remove_resolvconf='false'
[ -L "${1}/etc/resolv.conf" ] && remove_resolvconf='false'
[ "${2}" = '--no-resolvconf' ] && remove_resolvconf='false'

mount --bind /dev "${1}/dev"
mount --bind /proc "${1}/proc"
[ ! "${2}" = '--no-resolvconf' ] && cat '/etc/resolv.conf' > "${1}/etc/resolv.conf"

chroot "${1}" apt-get update
chroot "${1}" apt-get install linux-image-${arch} || update_grub='false'
chroot "${1}" apt-get clean
"${update_grub}" && chroot "${1}" update-grub

umount "${1}/dev"
umount "${1}/proc"
"${remove_resolvconf}" && rm "${1}/etc/resolv.conf"

exit 0
