#!/bin/sh

if [ ! -e "$(dirname "$(readlink -f "${0}")")/leafpad.tar.gz" ]; then
	echo 'Build leafpad first'
	exit 1
fi

if [ ! -e /var/tmp/.apps/.leafpad ]; then
	tar xf $(dirname "$(readlink -f "$0")")/leafpad.tar.gz -C /var/tmp/.apps
	FONTCONFIG_FILE=/var/tmp/.apps/.leafpad/etc/fonts/fonts.conf LD_LIBRARY_PATH=/var/tmp/.apps/.leafpad/lib /var/tmp/.apps/.leafpad/bin/leafpad-bin $@ &

	while ps -A | grep leafpad-bin > /dev/null 2>&1; do
		sleep 1
	done

	rm -r -f /var/tmp/.apps/.leafpad
else
	FONTCONFIG_FILE=/var/tmp/.apps/.leafpad/etc/fonts/fonts.conf LD_LIBRARY_PATH=/var/tmp/.apps/.leafpad/lib /var/tmp/.apps/.leafpad/bin/leafpad-bin $@
fi

exit 0
